name: 开启：推
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4

    # 1. 浅层克隆 Theos 核心
    - name: 克隆 Theos 环境
      run: |
        git clone --depth=1 --recursive https://github.com/theos/theos.git ~/theos
        echo "THEOS=~/theos" >> $GITHUB_ENV

    # 2. 直接挂载系统自带 SDK，彻底告别外网下载和解压报错！
    - name: 挂载系统官方 SDK
      run: |
        mkdir -p ~/theos/sdks
        SYS_SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
        ln -s "$SYS_SDK_PATH" ~/theos/sdks/iPhoneOS16.6.sdk
        echo "系统自带 SDK 路径: $SYS_SDK_PATH"

    # 3. 开始执行编译打包
    - name: 建造
      run: |
        export THEOS=~/theos
        export THEOS_PACKAGE_SCHEME=rootless
        make package SYSROOT=~/theos/sdks/iPhoneOS16.6.sdk
        
    # 4. 上传打包好的 .deb 文件
    - name: 上传成果物
      uses: actions/upload-artifact@v4
      with:
        name: ScreenshotIsland-DEB
        path: packages/*.deb
