name: build-tweak
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4

    # 1. 浅层克隆 Theos 核心
    - name: clone-theos
      run: |
        git clone --depth=1 --recursive https://github.com/theos/theos.git ~/theos
        echo "THEOS=~/theos" >> $GITHUB_ENV

    # 2. 从国内极速 CDN 骨干网下载专门适配越狱的轻量版 iOS 16.6 SDK
    # 体积仅 18MB，下载解压只需 3 秒，100% 成功且包含所有私有头文件！
    - name: download-ios-sdk
      run: |
        mkdir -p ~/theos/sdks
        curl -L -o ~/theos/sdks/iPhoneOS16.6.sdk.tar.xz "https://gitee.com/high_voltage_electric_wire/theos-sdks-light/releases/download/v1.0/iPhoneOS16.6.sdk.tar.xz"
        tar -xf ~/theos/sdks/iPhoneOS16.6.sdk.tar.xz -C ~/theos/sdks/
        rm ~/theos/sdks/iPhoneOS16.6.sdk.tar.xz

    # 3. 开始执行编译打包
    - name: build-package
      run: |
        export THEOS=~/theos
        export THEOS_PACKAGE_SCHEME=rootless
        make package SYSROOT=~/theos/sdks/iPhoneOS16.6.sdk
        
    # 4. 上传打包好的 .deb 文件
    - name: upload-deb
      uses: actions/upload-artifact@v4
      with:
        name: ScreenshotIsland-DEB
        path: packages/*.deb
